/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author kevin
 */
public class Calculadora extends javax.swing.JFrame {
    
    private int valor;
    private int ligado;
    private String[] calculadora = new String[9];
    private StringBuffer memoria = new StringBuffer();
    private boolean statusBtn;
    private int valorGerado;
    private int valorAcumulado;
    private String operacao;
    private boolean zerar;
    private boolean botaoAdcao;
    private boolean botaoSubtracao;
    private boolean botaoMultiplicacao;
    private boolean botaoDivisao;
    private boolean lock;
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLigado(1);
        this.setValor(this.getValor());
        this.setZerar(false);
        lblPainel.setVisible(false);
        btnLigar.setText("OFF");
        
        //Botoes
        this.setBotao(false);
        this.setBotaoAdcao(false);
        this.setBotaoSubtracao(false);
        this.setBotaoMultiplicacao(false);
        this.setBotaoDivisao(false);

    }
    
    public void setValor(int valor){
        this.valor = valor;
    }
    
    public int getValor(){
        return this.valor;
    }
    
    public void setLigado(int ligado){
        this.ligado = ligado;
    }
    
    public int getLigado(){
        return this.ligado;
    }
    
    public void setCalculadora(String[] calculadora){
        this.calculadora = calculadora;
    }
    
    public String[] getCalculadora(){
        return this.calculadora;
    }
    
    public void setZerar(boolean zerar){
        this.zerar = zerar;
    } 
    
    public boolean getZerar(){
        return this.zerar;
    }
    
    public void setLock(boolean lock){
        this.lock = lock;
    }
    
    public boolean getLock(){
        return this.lock;
    }
    
    /*BOTOES*/
    public void setBotao(boolean statusBtn){
        this.statusBtn = statusBtn;
    }
    
    public boolean getBotao(){
        return this.statusBtn;
    }
    
    public void setBotaoAdcao(boolean botaoAdcao){
        this.botaoAdcao = botaoAdcao;
    }
    
    public boolean getBotaoAdcao(){
        return this.botaoAdcao;
    }
    
    public void setBotaoSubtracao(boolean botaoSubtracao){
        this.botaoSubtracao = botaoSubtracao;
    }
    
    public boolean getBotaoSubtracao(){
        return this.botaoSubtracao;
    }
    
    public void setBotaoMultiplicacao(boolean botaoMultiplicacao){
        this.botaoMultiplicacao = botaoMultiplicacao;
    }
    
    public boolean getBotaoMultiplicacao(){
        return this.botaoMultiplicacao;
    }
    
    public void setBotaoDivisao(boolean botaoDivisao){
        this.botaoDivisao = botaoDivisao;
    }
    
    public boolean getBotaoDivisao(){
        return this.botaoDivisao;
    }
    
    public void setValorGerado(int valorGerado){
        this.valorGerado = valorGerado;
    }
    
    public int getValorGerado(){
        return this.valorGerado;
    }
    
    public void setValorAcumulado(int valorAcumulado){
        this.valorAcumulado = valorAcumulado;
    }
    
    public int getValorAcumulado(){
        return this.valorAcumulado;
    }
    
    public void setOperacao(String operacao){
        this.operacao = operacao;
    }
    
    public String getOperacao(){
        return this.operacao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visorCalculadora = new javax.swing.JPanel();
        lblPainel = new javax.swing.JLabel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnVirgula = new javax.swing.JButton();
        btnMultiplicacao = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        btnAdcao = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnLigar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        visorCalculadora.setBackground(new java.awt.Color(204, 255, 204));

        lblPainel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblPainel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPainel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPainelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout visorCalculadoraLayout = new javax.swing.GroupLayout(visorCalculadora);
        visorCalculadora.setLayout(visorCalculadoraLayout);
        visorCalculadoraLayout.setHorizontalGroup(
            visorCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visorCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        visorCalculadoraLayout.setVerticalGroup(
            visorCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visorCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn7.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btn0.setText("0");
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });

        btnVirgula.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnVirgula.setText(".");

        btnMultiplicacao.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnMultiplicacao.setText("x");
        btnMultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplicacaoMouseClicked(evt);
            }
        });

        btnDivisao.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnDivisao.setText("/");
        btnDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisaoMouseClicked(evt);
            }
        });

        btnAdcao.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnAdcao.setText("+");
        btnAdcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdcaoMouseClicked(evt);
            }
        });

        btnSubtracao.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnSubtracao.setText("-");
        btnSubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubtracaoMouseClicked(evt);
            }
        });
        btnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtracaoActionPerformed(evt);
            }
        });

        btnIgual.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualMouseClicked(evt);
            }
        });

        btnLigar.setText("ON");
        btnLigar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLigarMouseClicked(evt);
            }
        });

        btnLimpar.setText("CE");
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(visorCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn8)))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnLigar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visorCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLigar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4)
                            .addComponent(btnMultiplicacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVirgula)
                            .addComponent(btnAdcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIgual)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn9)
                            .addComponent(btnDivisao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn3)
                            .addComponent(btnSubtracao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubtracaoActionPerformed

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(7);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn7MouseClicked

    private void lblPainelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPainelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblPainelMouseClicked
    
    public void logicaVisor(){
        for(int i = 0; i < calculadora.length; i++){
            //System.out.println("Calculadora["+ (i + 1) +"] "+ calculadora[0]);
            
            // Verifica se algum botal foi pressionado e se a posicao do Array e diferente de null, para certificar que nao sera sobrescrito nenhum valor digitado
            if(this.getBotao() && calculadora[i] == null){
                // Insere o valor digitado dentro da posicao do Array
                calculadora[i] = Integer.toString(this.getValor());
                this.setBotao(false);
                
                // Armazena o valor do array dentro do Buff de Memoria
                memoria.append(calculadora[i]);
                lblPainel.setText(memoria.toString());
            }
        }
        /*for(int i = 0; i < calculadora.length; i++){
            System.out.print(calculadora[i] +" ");
        }
        System.out.println("");*/
    }
    
    public void zerarCalculadora(){
        this.setZerar(true);
        
        // Como forma de seguranca, somente se o botao limpar for pressionado, ira ativar essa condicao (Mas talveznao seja tao necessario assim, irei verificar mais tarde)
        if(this.getZerar()){
            int i = 0;
            
            // Acessa o Buff de memoria, e navega de posicao em posicao deletando o intem contido no index informado
            while(memoria.length() != 0){
                memoria.deleteCharAt(i);
                lblPainel.setText(memoria.toString());
                lblPainel.setText("0");
                
                /*System.out.println("Memoria deletada: "+ memoria);
                System.out.println("Comprimento da Memoria: "+ memoria.length());*/
                   
            }
            
            // Acessa o Array Calculadora, e muda todas as posicoes para null, mas sem passar esse novos valores para o Buff
            for(int j = 0; j < calculadora.length; j++){
                calculadora[j] = null;

                /*System.out.println("Valores do Array: "+ calculadora[j]);
                System.out.println("Memoria deletada: "+ memoria);
                System.out.println("Comprimento da Memoria: "+ memoria.length());*/
            }
            
            this.setZerar(false);
        }

    }
    
    public void salvarValor(){
        
        // Recebe a o valor do Buff de Memoria e converte para double para que possa ser utilizado em calculos
        if(this.getBotao()){
            this.setValorGerado(Integer.parseInt(memoria.toString()));
            //System.out.println(this.getValorGerado());
            
            // Verifica qual operador foi pressionado e aplica o operador correto, caso a caso
            switch(this.getOperacao()){
                // OBS.: Tem que zerar o [ACUMULADOR] caso clique para apagar os valores digitados
                case "+":
                    this.setValorAcumulado(this.getValorAcumulado() + this.getValorGerado());

                    // Limpa a memoria para que possa ser inserido um novo valor
                    this.zerarCalculadora();
                break;
                
                case "-":
                    this.setValorAcumulado(this.getValorGerado() - this.getValorAcumulado());

                    // Limpa a memoria para que possa ser inserido um novo valor
                    this.zerarCalculadora();
                break;
                
                case "x":
                    if(this.getValorAcumulado() == 0){
                        this.setValorAcumulado(1);
                    }
                    
                    this.setValorAcumulado(this.getValorAcumulado() * this.getValorGerado());
                    //System.out.println("Multipliacao: "+ this.getValorAcumulado());

                    // Limpa a memoria para que possa ser inserido um novo valor
                    this.zerarCalculadora();
                break;
                
                case "/":
                    if(this.getValorAcumulado() == 0){
                        this.setValorAcumulado(1);
                    }
                    
                    this.setValorAcumulado(this.getValorAcumulado() * this.getValorGerado());
                    //System.out.println("Divisao: "+ this.getValorAcumulado());

                    // Limpa a memoria para que possa ser inserido um novo valor
                    this.zerarCalculadora();
                break;
                
                case "=":
                    if(this.getBotaoAdcao()){
                        this.setValorAcumulado(this.getValorAcumulado() + this.getValorGerado());
                        
                        this.setBotaoAdcao(false);
                        
                    }else if(this.getBotaoDivisao()){
                        this.setValorAcumulado(this.getValorAcumulado() / this.getValorGerado());
                        
                        this.setBotaoDivisao(false);
                        
                    }else if(this.getBotaoMultiplicacao()){
                        this.setValorAcumulado(this.getValorAcumulado() * this.getValorGerado());
                        
                        this.setBotaoMultiplicacao(false);
                        
                    }else if(this.getBotaoSubtracao()){
                        this.setValorAcumulado(this.getValorAcumulado() - this.getValorGerado());
                        
                        this.setBotaoSubtracao(false);
                    }
                    
                    // Limpa a memoria para que possa ser inserido um novo valor
                    this.zerarCalculadora();
                    
                    lblPainel.setText(Integer.toString(this.getValorAcumulado()));
                break;
                
                default:
                    System.out.println("A operacao nao pode ser concluida, por um erro de logica ;-;");
                break;
            }
            
            //System.out.println("O valor Acumulado e: "+ this.getValorAcumulado());
            this.setBotao(false);
        }
    }
    
    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);

        this.setValor(4);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn4MouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(1);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn1MouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(0);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn0MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(8);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn8MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(5);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn5MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(2);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn2MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(9);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn9MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(6);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn6MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setValor(3);
        lblPainel.setText(Integer.toString(this.getValor()));
        
        this.logicaVisor();
    }//GEN-LAST:event_btn3MouseClicked

    private void btnLigarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLigarMouseClicked
        // TODO add your handling code here:
        
        this.setLigado(this.getLigado() + 1);
        
        if(this.getLigado() % 2 == 0){
            btnLigar.setText("ON");
            lblPainel.setVisible(true);
            //this.setValor(this.getValor());
        }else{
            this.setValor(0);
            btnLigar.setText("OFF");
            lblPainel.setText(Integer.toString(this.getValor()));
            lblPainel.setVisible(false);
        }
    }//GEN-LAST:event_btnLigarMouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        this.setValorAcumulado(0);
        this.setValor(0);
        
        lblPainel.setText(Integer.toString(this.getValor()));
        
        // Zera o array da calculadora, e instancia todas as posicoes da memoria como sendo null
        this.zerarCalculadora();
        
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnAdcaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdcaoMouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        this.setBotaoAdcao(true);
        
        this.setOperacao("+");
        
        // Da o input para armazenar os valores digitados dentro da variavel
        this.salvarValor();
    }//GEN-LAST:event_btnAdcaoMouseClicked

    private void btnIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        
        this.setOperacao("=");
        
        // Da o input para armazenar os valores digitados dentro da variavel
        this.salvarValor();
    }//GEN-LAST:event_btnIgualMouseClicked

    private void btnSubtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubtracaoMouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        this.setBotaoSubtracao(true);
        
        this.setOperacao("-");
        
        // Da o input para armazenar os valores digitados dentro da variavel
        this.salvarValor();
    }//GEN-LAST:event_btnSubtracaoMouseClicked

    private void btnMultiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicacaoMouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        this.setBotaoMultiplicacao(true);
        
        this.setOperacao("x");
        
        // Da o input para armazenar os valores digitados dentro da variavel
        this.salvarValor();
    }//GEN-LAST:event_btnMultiplicacaoMouseClicked

    private void btnDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisaoMouseClicked
        // TODO add your handling code here:
        this.setBotao(true);
        this.setBotaoDivisao(true);
        
        this.setOperacao("/");
        
        // Da o input para armazenar os valores digitados dentro da variavel
        this.salvarValor();
    }//GEN-LAST:event_btnDivisaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdcao;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLigar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JButton btnVirgula;
    private javax.swing.JLabel lblPainel;
    private javax.swing.JPanel visorCalculadora;
    // End of variables declaration//GEN-END:variables
}
